### ISSUE TITLE
using load_CB_speeches function

### ISSUE THREAD

**Issue by Tevdokimova** [bis-med-it/gingado#19]
I have tried to access central banks' speeches via gingado. 

I used the following code for that: 
pip install gingado
import gingado
speeches = load_CB_speeches(2020)
speeches.head()

And got an error "name 'load_CB_speeches' is not defined"

I managed to use the function when I copied the full code from the following link into the python cell https://github.com/bis-med-it/gingado/blob/main/gingado/datasets.py

What could cause the issue?

**Comment by dkgaraujo** [comment]
Many thanks @Tevdokimova for filing this issue.

Please try the following code:

```
from gingado.datasets import load_CB_speeches
speeches = load_CB_speeches(2020)
speeches.head()
```
